export const GET_USERS_REQUEST = "GET_USERS_REQUEST";
export const GET_USERS_RESPONSE = "GET_USERS_RESPONSE";
export const SIGN_IN = 'SIGN_IN';
export const SIGN_OUT = 'SIGN_OUT';
export const GET_IMAGES_REQUEST = 'GET_IMAGES_REQUEST';
export const GET_IMAGES_RESPONSE = 'GET_IMAGES_RESPONSE';